
package com.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentImpl", targetNamespace = "http://ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://ws.com/", className = "com.ws.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://ws.com/", className = "com.ws.GetNameResponse")
    @Action(input = "http://ws.com/StudentImpl/getNameRequest", output = "http://ws.com/StudentImpl/getNameResponse")
    public String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
